/* I MART Seller Center frontend. Uses the existing seller JWT and API routes. */
(function(){
"use strict";
const SELLER_CENTER_API_BASE = (() => { if (window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1" || window.location.protocol === "file:") return "http://localhost:5000/api"; return "https://i-mart-backend.onrender.com/api"; })();
const state = { products: [], orders: [], seller: null, revenue: 0 };
const $ = id => document.getElementById(id);
const token = () => localStorage.getItem("sellerToken");
const headers = (json=true) => { const h={Authorization:`Bearer ${token()}`}; if(json) h["Content-Type"]="application/json"; return h; };
const money = v => `GH₵${Number(v||0).toFixed(2)}`;
const escapeHtml = value => String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
const apiOrigin = SELLER_CENTER_API_BASE.replace(/\/api$/,"");
const imageUrl = path => path ? (path.startsWith("http")?path:`${apiOrigin}${path}`) : "images/placeholder.png";
function toast(message,error=false){const el=$("sc-toast");if(!el)return;el.textContent=message;el.className=`sc-toast show${error?" error":""}`;clearTimeout(window.__scToastTimer);window.__scToastTimer=setTimeout(()=>el.className="sc-toast",3500);}
function showSection(id){document.querySelectorAll(".sc-section").forEach(s=>s.classList.toggle("active",s.id===`section-${id}`));document.querySelectorAll(".sc-nav button[data-section]").forEach(b=>b.classList.toggle("active",b.dataset.section===id));const titles={overview:"Overview",products:"Products",add:"Add Product",orders:"Orders",wallet:"Wallet",analytics:"Analytics",store:"My Store",resellers:"Resellers",subscription:"Subscription",settings:"Settings"};$("sc-topbar-title").textContent=titles[id]||"Seller Center";history.replaceState(null,"",`#${id}`);$("sc-sidebar").classList.remove("open");$("sc-overlay").classList.remove("show");if(id==="products")renderProducts();if(id==="orders")renderOrders();}
function setupNavigation(){document.querySelectorAll(".sc-nav button[data-section]").forEach(btn=>btn.addEventListener("click",()=>showSection(btn.dataset.section)));$("sc-mobile-toggle").addEventListener("click",()=>{$("sc-sidebar").classList.add("open");$("sc-overlay").classList.add("show")});$("sc-overlay").addEventListener("click",()=>{$("sc-sidebar").classList.remove("open");$("sc-overlay").classList.remove("show")});$("sc-logout").addEventListener("click",logout);showSection(location.hash.replace("#","")||"overview");}
function logout(){localStorage.removeItem("sellerToken");localStorage.removeItem("currentSeller");window.location.href="seller-login.html";} window.logoutSeller=logout;
async function api(path,options={}){const response=await fetch(`${SELLER_CENTER_API_BASE}${path}`,{...options,headers:{...headers(options.body instanceof FormData?false:true),...(options.headers||{})}});let data={};try{data=await response.json()}catch(_){}if(!response.ok||data.success===false)throw new Error(data.message||`Request failed (${response.status})`);return data;}
async function loadAll(){if(!token()){window.location.href="seller-login.html";return;}try{const [profile,stats,products,orders]=await Promise.all([api("/sellers/profile"),api("/sellers/stats"),api("/products/seller/my-products"),api("/orders/seller")]);state.seller=profile.seller||JSON.parse(localStorage.getItem("currentSeller")||"null")||{};state.products=products.products||[];state.orders=orders.orders||[];state.revenue=Number(stats.stats?.totalRevenue||0);localStorage.setItem("currentSeller",JSON.stringify(state.seller));renderProfile();renderStats(stats.stats||{});renderProducts();renderOrders();renderWallet();renderAnalytics();renderStore();renderSubscription();renderSettings();renderOverview();}catch(error){console.error(error);toast(error.message||"Unable to load seller center.",true);$("overview-error").textContent="Some live data could not be loaded. Please refresh and try again.";}}
function renderProfile(){const s=state.seller||{};$("seller-name").textContent=s.fullName||"Seller";$("shop-name").textContent=s.shopName||"—";$("seller-email").textContent=s.email||"—";$("seller-phone").textContent=s.phone||"—";$("seller-status").textContent=s.status||"Unknown";$("avatar").textContent=(s.fullName||"S").trim().charAt(0).toUpperCase();$("account-badge").textContent=s.status||"Unknown";$("account-badge").className=`sc-badge ${s.status==="Active"?"success":"danger"}`;$("subscription-badge").textContent=s.billingStatus?`Billing: ${s.billingStatus}`:(s.subscription||"Basic");$("subscription-badge").className=`sc-badge ${s.billingStatus==="Paid"?"success":"warning"}`;$("topbar-shop").textContent=s.shopName||"Seller";}
function renderStats(stats){const totalProducts=Number(stats.productsCount??state.products.length),totalOrders=Number(stats.ordersCount??state.orders.length),revenue=Number(stats.totalRevenue??state.revenue),pending=state.orders.filter(o=>(o.status||"Pending")==="Pending").length,completed=state.orders.filter(o=>(o.status||"")==="Delivered").length,out=state.products.filter(p=>Number(p.stock)<=0||p.status==="Out of Stock").length;$("stat-products").textContent=totalProducts;$("stat-orders").textContent=totalOrders;$("stat-revenue").textContent=money(revenue);$("stat-pending").textContent=pending;$("stat-completed").textContent=completed;$("stat-out").textContent=out;}
function sellerOrderValue(order){const sid=String(state.seller?._id||state.seller?.id||"");return(order.items||[]).filter(i=>!i.seller||String(i.seller?._id||i.seller)===sid).reduce((s,i)=>s+Number(i.price||0)*Number(i.quantity||0),0);}
function orderProductText(order){return(order.items||[]).map(i=>`${i.product?.name||"Product"} × ${i.quantity||0}`).join(", ")||"—";}
function renderOverview(){const pb=$("recent-products-body"),ob=$("recent-orders-body");pb.innerHTML=state.products.slice(0,5).map(p=>`<tr><td><div class="sc-product-cell"><img src="${escapeHtml(imageUrl(p.image))}" alt="${escapeHtml(p.name)}"><strong>${escapeHtml(p.name)}</strong></div></td><td>${money(p.price)}</td><td>${Number(p.stock||0)}</td><td><span class="sc-badge ${p.status==="Active"?"success":p.status==="Out of Stock"?"danger":"warning"}">${escapeHtml(p.status||"Active")}</span></td><td><a class="sc-btn secondary" href="edit-product.html?id=${encodeURIComponent(p._id)}">Edit</a></td></tr>`).join("")||`<tr><td colspan="5" class="sc-empty">No products yet.</td></tr>`;ob.innerHTML=state.orders.slice(0,5).map(o=>`<tr><td>#${escapeHtml(String(o._id||"").slice(-8))}</td><td>${escapeHtml(o.user?.fullName||"Customer")}</td><td>${escapeHtml(orderProductText(o))}</td><td>${money(sellerOrderValue(o))}</td><td><span class="sc-badge">${escapeHtml(o.status||"Pending")}</span></td></tr>`).join("")||`<tr><td colspan="5" class="sc-empty">No orders yet.</td></tr>`;}
function renderProducts(){const search=$( "product-search")?.value?.toLowerCase().trim()||"",filter=$("product-filter")?.value||"all",sort=$("product-sort")?.value||"newest";let list=state.products.filter(p=>`${p.name} ${p.category} ${p.status}`.toLowerCase().includes(search));if(filter!=="all")list=list.filter(p=>filter==="out"?(Number(p.stock)<=0||p.status==="Out of Stock"):p.status===filter);list.sort((a,b)=>sort==="price-low"?Number(a.price)-Number(b.price):sort==="price-high"?Number(b.price)-Number(a.price):sort==="stock"?Number(a.stock)-Number(b.stock):new Date(b.createdAt||0)-new Date(a.createdAt||0));const body=$("products-body");if(!list.length){body.innerHTML=`<tr><td colspan="7" class="sc-empty">No products match your filters.</td></tr>`;return;}body.innerHTML=list.map(p=>`<tr><td><div class="sc-product-cell"><img src="${escapeHtml(imageUrl(p.image))}" alt="${escapeHtml(p.name)}"><div><strong>${escapeHtml(p.name)}</strong><div class="sc-muted">${escapeHtml(p.category||"Uncategorized")}</div></div></div></td><td>${money(p.price)}</td><td>${Number(p.stock||0)}</td><td><span class="sc-badge ${p.status==="Active"?"success":p.status==="Out of Stock"?"danger":"warning"}">${escapeHtml(p.status||"Active")}</span></td><td>${Number(p.totalSales||0)}</td><td>${new Date(p.createdAt||Date.now()).toLocaleDateString()}</td><td><div class="sc-actions"><a class="sc-btn secondary" href="edit-product.html?id=${encodeURIComponent(p._id)}">Edit</a><button class="sc-btn danger" data-delete-product="${escapeHtml(p._id)}">Delete</button></div></td></tr>`).join("");}
async function deleteProduct(id){if(!confirm("Delete this product? This cannot be undone."))return;try{toast("Deleting product…");await api(`/products/${encodeURIComponent(id)}`,{method:"DELETE"});state.products=state.products.filter(p=>p._id!==id);renderProducts();renderOverview();renderStats({productsCount:state.products.length,ordersCount:state.orders.length,totalRevenue:state.revenue});toast("Product deleted successfully.");}catch(e){toast(e.message,true);}}
document.addEventListener("click",e=>{const id=e.target.closest("[data-delete-product]")?.dataset.deleteProduct;if(id)deleteProduct(id);});
function renderOrders(){const search=$( "order-search")?.value?.toLowerCase().trim()||"",filter=$("order-filter")?.value||"all";let list=state.orders.filter(o=>`${o._id} ${o.user?.fullName||""} ${orderProductText(o)}`.toLowerCase().includes(search));if(filter!=="all")list=list.filter(o=>(o.status||"Pending")===filter);const body=$("orders-body");if(!list.length){body.innerHTML=`<tr><td colspan="8" class="sc-empty">No orders match your filters.</td></tr>`;return;}body.innerHTML=list.map(o=>{const status=o.status||"Pending";return`<tr><td>#${escapeHtml(String(o._id||"").slice(-8))}</td><td>${escapeHtml(o.user?.fullName||"Customer")}</td><td>${escapeHtml(orderProductText(o))}</td><td>${(o.items||[]).reduce((n,i)=>n+Number(i.quantity||0),0)}</td><td>${money(sellerOrderValue(o))}</td><td>${escapeHtml(o.paymentStatus||"Pending")}</td><td><select class="sc-select sc-order-status" data-order-status="${escapeHtml(o._id)}"><option ${status==="Pending"?"selected":""}>Pending</option><option ${status==="Processing"?"selected":""}>Processing</option><option ${status==="Shipped"?"selected":""}>Shipped</option><option ${status==="Delivered"?"selected":""}>Delivered</option><option ${status==="Cancelled"?"selected":""}>Cancelled</option></select></td><td>${new Date(o.createdAt||Date.now()).toLocaleDateString()}</td></tr>`}).join("");}
async function updateOrderStatus(id,status){try{toast("Updating order…");await api(`/orders/${encodeURIComponent(id)}`,{method:"PUT",body:JSON.stringify({orderStatus:status})});const order=state.orders.find(o=>o._id===id);if(order)order.status=status;renderOrders();renderOverview();renderStats({productsCount:state.products.length,ordersCount:state.orders.length,totalRevenue:state.revenue});renderWallet();renderAnalytics();toast("Order status updated.");}catch(e){toast(e.message,true);renderOrders();}}
document.addEventListener("change",e=>{const id=e.target.closest("[data-order-status]")?.dataset.orderStatus;if(id)updateOrderStatus(id,e.target.value);});
function renderWallet(){const revenue=state.revenue,completed=state.orders.filter(o=>(o.status||"")==="Delivered").reduce((s,o)=>s+sellerOrderValue(o),0),pending=state.orders.filter(o=>["Pending","Processing","Shipped"].includes(o.status||"Pending")).reduce((s,o)=>s+sellerOrderValue(o),0);$("wallet-revenue").textContent=money(revenue);$("wallet-available").textContent=money(completed);$("wallet-pending").textContent=money(pending);$("wallet-fee").textContent=money(state.seller?.monthlyFee);$("wallet-sales").textContent=state.orders.filter(o=>(o.status||"")==="Delivered").length;const rows=state.orders.slice(0,10).map(o=>`<tr><td>#${escapeHtml(String(o._id||"").slice(-8))}</td><td>Sale</td><td>${money(sellerOrderValue(o))}</td><td>${escapeHtml(o.status||"Pending")}</td><td>${new Date(o.createdAt||Date.now()).toLocaleDateString()}</td></tr>`);$("transactions-body").innerHTML=rows.length?rows.join(""):`<tr><td colspan="5" class="sc-empty">No sales transactions yet.</td></tr>`;}
function renderAnalytics(){const best=[...state.products].sort((a,b)=>Number(b.totalSales||0)-Number(a.totalSales||0)).slice(0,5),low=state.products.filter(p=>Number(p.stock||0)<=5).sort((a,b)=>Number(a.stock||0)-Number(b.stock||0)).slice(0,5);$("best-products").innerHTML=best.length?best.map(p=>`<div class="sc-kpi-row"><span>${escapeHtml(p.name)}</span><strong>${Number(p.totalSales||0)} sales</strong></div>`).join(""):`<div class="sc-empty">No product sales data yet.</div>`;$("low-products").innerHTML=low.length?low.map(p=>`<div class="sc-kpi-row"><span>${escapeHtml(p.name)}</span><strong>${Number(p.stock||0)} left</strong></div>`).join(""):`<div class="sc-empty">No low-stock products.</div>`;$("analytics-products").textContent=state.products.length;$("analytics-orders").textContent=state.orders.length;$("analytics-revenue").textContent=money(state.revenue);$("analytics-pending").textContent=state.orders.filter(o=>(o.status||"Pending")==="Pending").length;$("analytics-completed").textContent=state.orders.filter(o=>(o.status||"")==="Delivered").length;}
function renderStore(){const s=state.seller||{};$("store-name").textContent=s.shopName||"—";$("store-seller").textContent=s.fullName||"—";$("store-email").textContent=s.email||"—";$("store-status").textContent=s.status||"—";$("store-count").textContent=state.products.length;$("store-products").innerHTML=state.products.slice(0,6).map(p=>`<div class="sc-product-cell"><img src="${escapeHtml(imageUrl(p.image))}" alt="${escapeHtml(p.name)}"><div><strong>${escapeHtml(p.name)}</strong><div class="sc-muted">${money(p.price)} · ${Number(p.stock||0)} stock</div></div></div>`).join("")||`<div class="sc-empty">No products in your store yet.</div>`;}
function renderSubscription(){const s=state.seller||{};$("sub-plan").textContent=s.subscription||"Basic";$("sub-fee").textContent=money(s.monthlyFee);$("sub-status").textContent=s.status||"—";$("sub-billing").textContent=s.billingStatus||"—";$("sub-next").textContent=s.nextBillingDate?new Date(s.nextBillingDate).toLocaleDateString():"—";$("sub-last").textContent=s.lastPaymentDate?new Date(s.lastPaymentDate).toLocaleDateString():"—";}
function renderSettings(){const s=state.seller||{};$("settings-fullname").value=s.fullName||"";$("settings-shopname").value=s.shopName||"";$("settings-email").value=s.email||"";$("settings-phone").value=s.phone||"";}
async function saveSettings(){const payload={fullName:$("settings-fullname").value.trim(),shopName:$("settings-shopname").value.trim(),email:$("settings-email").value.trim().toLowerCase(),phone:$("settings-phone").value.trim()};if(!payload.fullName||!payload.shopName||!payload.email||!payload.phone){toast("Please complete all seller details.",true);return;}const btn=$("save-settings");btn.disabled=true;try{const data=await api("/sellers/profile",{method:"PUT",body:JSON.stringify(payload)});state.seller=data.seller;localStorage.setItem("currentSeller",JSON.stringify(state.seller));renderProfile();renderSubscription();toast("Seller settings saved.");}catch(e){toast(e.message,true);}finally{btn.disabled=false;}}
async function addProduct(e){e.preventDefault();const form=$("add-product-form"),btn=$("add-product-submit"),formData=new FormData(form);btn.disabled=true;btn.textContent="Adding…";try{const data=await api("/products/add",{method:"POST",body:formData});state.products.unshift(data.product);form.reset();$("image-preview").style.display="none";renderProducts();renderOverview();renderStats({productsCount:state.products.length,ordersCount:state.orders.length,totalRevenue:state.revenue});renderAnalytics();renderStore();toast("Product added successfully.");showSection("products");}catch(e){toast(e.message,true);}finally{btn.disabled=false;btn.textContent="Add Product";}}
async function renewSubscription(){const btn=$("renew-subscription");btn.disabled=true;btn.textContent="Opening Paystack…";try{const data=await api("/subscription/initialize",{method:"POST",body:JSON.stringify({})});if(data.authorization_url)window.location.href=data.authorization_url;else throw new Error("Payment link was not returned.");}catch(e){toast(e.message,true);btn.disabled=false;btn.textContent="Renew / Manage Subscription";}}
document.addEventListener("DOMContentLoaded",()=>{setupNavigation();$("product-search").addEventListener("input",renderProducts);$("product-filter").addEventListener("change",renderProducts);$("product-sort").addEventListener("change",renderProducts);$("order-search").addEventListener("input",renderOrders);$("order-filter").addEventListener("change",renderOrders);$("add-product-form").addEventListener("submit",addProduct);$("image-input").addEventListener("change",()=>{const f=$("image-input").files[0];if(!f)return;$("image-preview").src=URL.createObjectURL(f);$("image-preview").style.display="block"});$("save-settings").addEventListener("click",saveSettings);$("renew-subscription").addEventListener("click",renewSubscription);loadAll();});
})();
